### ISSUE TITLE
Error: dial tcp :465: getsockopt: connection refused

### ISSUE THREAD

**Issue by pokurivijay** [rykov/paperboy#16]
I am getting the following error while trying to send the email.

Error: dial tcp :465: getsockopt: connection refused

how to set a custom port?

I already tried like following

```
[smtp]
  url = "smtp.socketlabs.com"
  port = "25"
```

and 

```
[smtp]
  url = "smtp.socketlabs.com:25"
```

i am using MacOS.

**Comment by rykov** [comment]
Looks like those not technically URL values, and they are not parsed correctly. Be sure to use `smtp://` or `smtps://` prefix to make sure the URL is parsed correctly.

**Comment by rykov** [comment]
Notice here how in both cases the value is actually parsed into either `.Path` or `.Scheme` in the URL, rather than into `.Host` -- that's causing the problem.

https://play.golang.org/p/oAFKKuj7Zrd
